# Generated by Django 4.2.7 on 2025-08-01 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('CRIADO', 'Agendamento Criado'), ('STATUS_ALTERADO', 'Status Alterado'), ('DADOS_ALTERADOS', 'Dados Alterados'), ('CANCELADO', 'Cancelado'), ('REAGENDADO', 'Reagendado')], max_length=20, verbose_name='Tipo de Ação')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('status_anterior', models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('NAO_COMPARECEU', 'Não Compareceu')], max_length=20, null=True, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('NAO_COMPARECEU', 'Não Compareceu')], max_length=20, null=True, verbose_name='Status Novo')),
                ('usuario', models.CharField(default='Sistema', help_text='Quem fez a alteração', max_length=100, verbose_name='Usuário')),
                ('data_acao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='appointments.agendamento', verbose_name='Agendamento')),
            ],
            options={
                'verbose_name': 'Histórico de Agendamento',
                'verbose_name_plural': 'Históricos de Agendamentos',
                'ordering': ['-data_acao'],
                'indexes': [models.Index(fields=['agendamento', '-data_acao'], name='appointment_agendam_933407_idx')],
            },
        ),
    ]
