# Generated by Django 4.2.7 on 2025-08-01 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_historicoagendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Todos os serviços têm duração padrão de 60 minutos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duração (minutos)'),
        ),
    ]
